# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Template-Plugin-PodSimple
version:      1.010
version_from: lib/Template/Plugin/PodSimple.pm
installdirs:  site
requires:
    Pod::Simple:                   2.05
    Template::Plugin:              0
    Test::Simple:                  0.44

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.21
